### ISSUE TITLE
boros into 2263

### ISSUE THREAD

**Issue by datapolitan** [datapolitan/DOT_GIS#48]

**Comment by eapappas** [comment]
@datapolitan - new nybb_2263.shp is there.  I simply renamed the zip file that was in the data folder as _old, and called the new zip file boros.zip, so the slides don't need adjustment.  Inside, they are called nybb_2263.xxx.

As an aside, the screen shot of the open vector layer dialog is confusing.  The file with the .shp extension is identified an XML file, and the one without an extension is identified as the SHP file.  Confused and confusing.  Assume you're going to explain this because I don't even understand it.  

![image](https://cloud.githubusercontent.com/assets/10843911/14449745/e852dfc2-0044-11e6-8636-04726fc246e0.png)

**Comment by datapolitan** [comment]
@eapappas Thanks for making the change. The confusion can't be helped. .shp is a common extension and hidden in the system by default. We'll have people make the mistake of clicking on the wrong file and then tell them to click on something else.
